binop_separator              = "Back"
enum_discrim_align_threshold = 30
license_template_path        = "rustfmt.license-template"
max_width                    = 140
overflow_delimited_expr      = true
reorder_impl_items           = true
struct_field_align_threshold = 30
unstable_features            = true
use_field_init_shorthand     = true
version                      = "Two"
where_single_line            = true
