on: [push, pull_request]

name: CI

jobs:
    test:
      name: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - run: cargo test --all-features
    format:
      name: code format
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly
            components: rustfmt
        - run: cargo +nightly fmt -- --check
